if ( exists("takedown") ) takedown()
source("tests/test.R")
setup()
mod <- openModel("JRSPM")
rs <- mod$results()
cat("Initial selection (all)\n")
s <- rs$select()
print(length(s$selection))
cat("Finding dvmt in Year groups, plus any variable with 'bus'\n")
t <- s$find("dvmt",Group="Year")$and(s$find("bus"))
print(t)
cat("Adding Global/Marea/LambdaAdj\n")
u <- t$add("Global/Marea/LambdaAdj")
print(u)
cat("Removing 2010/Marea/BusDvmt\n")
t <- u$remove("2010/Marea/BusDvmt")
print(t)
cat("Removing 374\n")
u <- t$remove(374)
print(data.frame(name=u$fields(),row=u$selection))
