.testStep <- function (msg) cat("\n",msg,"...\n",sep="")

# The compare function uses the compareDF package

if ( ! "compareDF" %in% installed.packages()[,'Package']) {
  lib = .libPaths()[length(.libPaths())]
  install.packages("compareDF")
}
requireNamespace("compareDF")

# Items generated by modules using IPF:
#   # Outputs from PredictHousing:
#   Year$Household$HouseType <- unname(HouseType_Hh)
#   Year$Bzone$SF <- as.integer(unname(SF_Bz))
#   Year$Bzone$MF <- as.integer(unname(MF_Bz))
#   Year$Bzone$GQ <- as.integer(unname(GQ_Bz))
#   Year$Bzone$Pop <- as.integer(unname(Pop_Bz))
#   Year$Bzone$NumHh <- as.integer(unname(NumHh_Bz))
#   Year$Bzone$NumWkr <- as.integer(unname(NumWkr_Bz))
# 
#   # Outputs from LocateEmployment
#   Year$Bzone$TotEmp <- as.integer(unname(TotEmp_Bz))
#   Year$Bzone$RetEmp <- as.integer(unname(RetEmp_Bz))
#   Year$Bzone$SvcEmp <- as.integer(unname(SvcEmp_Bz))
#   Year$Worker$Bzone <- WrkBzone_
#   Year$Worker$Azone <- WrkAzone_
#   Year$Worker$Marea <- WrkMarea_
#   Year$Worker$DistanceToWork <- DistToWork_
# 
#   # Outputs from AssignParkingRestrictions
#   Year$Household <- list(
#     FreeParkingSpaces = as.integer(PkgSp_Hh),
#     ParkingUnitCost = CostPerSpace_Hh,
#     OtherParkingCost = OtherPkgCost_Hh
#   )
#   Year$Worker <- list(
#     PaysForParking = as.integer(DoesPay_Wk),
#     IsCashOut = as.integer(IsCashOut_Wk),
#     ParkingCost = CostPerSpace_Wk
#   )

# Tables:
#   Year$BZone c("Bzone", "SF", "MF", "GQ", "TotEmp", "RetEmp", "SvcEmp", "Pop", "NumHH", "NumWkr")
#   Year$Household c( "HhID", "HouseType", "FreeParkingSpaces", "ParkingUnitCost", "OtherParkingCost" ),
#   Year$Worker c( "WkrID", "BZone", "AZone", "Marea", "DistanceToWork", "PaysForParking", "IsCashOut", "ParkingCost" )

compare_ipf <- function(unfixed,fixed) {
  # unfixed and fixed are lists of a VEModel and a stage name
  # results will be retrieved and compared
  .testStep("Model index for relevant modules")
  mod <- unfixed$Model
  cat("Unfixed:",unfixed$Stage,"\n")
  results.unfixed <- unfixed$Model$results(unfixed$Stage)
  cat("Fixed:",unfixed$Stage,"\n")
  results.fixed <- fixed$Model$results(fixed$Stage)
  
  fn.hh    <- c("HhId", "HouseType", "FreeParkingSpaces", "ParkingUnitCost", "OtherParkingCost")
  fn.bzone <- c("Bzone", "SF", "MF", "GQ", "TotEmp", "RetEmp", "SvcEmp", "Pop", "NumHH", "NumWkr")
  fn.wkr   <- c("WkrID", "BZone", "AZone", "Marea", "DistanceToWork", "PaysForParking", "IsCashOut", "ParkingCost")

  # Get data.frame with results from each stage for desired tables/fields
  hh.unfixed    <- results.unfixed$find( Group="2038", Table="Household", Name=fn.hh )
  hh.unfixed    <- hh.unfixed$extract(saveTo=FALSE)$`2038.Household`

  hh.fixed      <- results.fixed$select()$find( Group="2038", Table="Household", Name=fn.hh )
  hh.fixed      <- hh.fixed$extract(saveTo=FALSE)$`2038.Household`

  bzone.unfixed <- results.unfixed$select()$find( Group="2038", Table="Bzone", Name=fn.bzone )
  bzone.unfixed <- bzone.unfixed$extract(saveTo=FALSE)$`2038.Bzone`

  bzone.fixed   <- results.fixed$select()$find( Group="2038", Table="Bzone", Name=fn.bzone )
  bzone.fixed   <- bzone.fixed$extract(saveTo=FALSE)$`2038.Bzone`

  wkr.unfixed   <- results.unfixed$select()$find( Group="2038", Table="Worker", Name=fn.wkr )
  wkr.unfixed   <- wkr.unfixed$extract(saveTo=FALSE)$`2038.Worker`

  wkr.fixed     <- results.fixed$select()$find( Group="2038", Table="Worker", Name=fn.wkr )
  wkr.fixed     <- wkr.fixed$extract(saveTo=FALSE)$`2038.Worker`

  hh.comp    <- suppressWarnings(compareDF::compare_df(hh.unfixed,hh.fixed,stop_on_error=F))
  cat("Household comparison:\n")
  print(hh.comp)
  bzone.comp <- suppressWarnings(compareDF::compare_df(bzone.unfixed,bzone.fixed,stop_on_error=F))
  cat("Bzone comparison:\n")
  print(bzone.comp)
  wkr.comp   <- suppressWarnings(compareDF::compare_df(wkr.unfixed,wkr.fixed,stop_on_error=F))
  cat("Worker comparison:\n")
  print(wkr.comp)

  return(
    list(
      cmp = list(
        hh.comp = hh.comp,
        bzone.comp = bzone.comp,
        wkr.comp = wkr.comp
      ),
      df = list(
        hh.unfixed=hh.unfixed, 
        hh.fixed=hh.fixed,     
        bzone.unfixed=bzone.unfixed,
        bzone.fixed=bzone.fixed,
        wkr.unfixed=wkr.unfixed,
        wkr.fixed=wkr.fixed
      )
    )
  )

  # Use the extract function on results for unfixed and fixed stages
  # Pull out Bzone, Household and Worker as noted above.

  # Make s eet of data.frames and then do some comparisons on them
  #  - how many rows are different for the same field
  #  - if any differences, how big is the % RMSE for the "fixed" version
  #  - many need to run another test on the full model if this one shows
  #    more than trivial differences - there we would look at DVMT by
  #    Region/Azone/Bzone...
}

test_model <- function(modelName=NULL,model="VERSPM",variant="test-ipf",log="warn",reset=FALSE) {
  # load and run a test model from this package
  if ( is.null(modelName) ) {
    .testStep(paste("Install model",model,"variant",variant))
    modelName <- paste(model,variant,sep="-")
    modelPath <- file.path("models",modelName)
    if ( reset && dir.exists(modelPath) ) {
      unlink(modelPath,recursive=TRUE)
    }
    mod <- if ( ! dir.exists(modelPath) ) {
      installModel(model,variant=variant,modelPath=modelName,log=log)
    } else {
      openModel(modelName,log=log)
    }

    .testStep("Run the model")
    mod$run(if(reset)"reset"else"continue") # white space? Who needs whitespace?
  } else {
    mod <- openModel(modelName,log=log)
    if ( ! mod$valid() ) {
      stop("Could not open model:",modelName)
    }
    .testStep(paste("Running",modelName))
    mod$run(if(reset)"reset"else"continue")
  }

  .testStep("Compare the results")
  modIndex <- compare_ipf(unfixed=list(Model=mod,Stage="ipf-broken"),fixed=list(Model=mod,Stage="ipf-fixed"))
  return( invisible(list(index=modIndex,model=mod)) )
}
