---
title: "Introduction to VERRSPM_Scenario"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to VETRSPM_Scenario}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Overview

Strategic planning often requires the assessment of large numbers of future scenarios, each assessing a different combination of prioritizations, policy decisions, and constraints. The VEScenarios module provides the capability to quickly set up, run, and visualize large numbers of VERSPM scenarios using a baseline scenario combined with multiple changes to model inputs. 

Both VERSPM and VERPAT models are capable of running multiple scenarios efficiently


### Scenario manager database
The first step to run the VERSPM_scnerios is to build the scenario manager database. A sample file is 
located in `scenario_root/verspm_scenario_manager.csv`. Scenarios should be defined in this table with the same format. 
At first level, you should define the strategies you want to run. 

These are the current list of VERSPM_Scenarios strategies:


* **Community Design** :  Policies that seek to enable shorter trips and alternate modes such as promotion of mixed use land use, transit service, bicycling, and parking management. ( group of L, B, P , T ) 
* **Marketing/Incentive** : Policies that improve driving efficiency such as eco driving,and Intelligent Transportation System efforts, as well as programs that reduce auto demand such as carsharing, and home or work-based transportation demand management.( group of D, E ) 
* **Pricing : Policies** that move towards true cost pricing such as road user fees to pay for the cost of operating, maintaining and improving roads, pay-as-you-drive (PAYD) insurance, and environmental impact fees such as a carbon tax. ( C )
* **Vehicles/Fuels** : Factors representing changes to future vehicles and fuels ( group of V, F ) 
* **Income** : Context factor on the assumed growth of statewide average per capita income ( I )

Each strategy covers couple of categories in a lower level.

These are the current list of VERSPM_Scenarios categories:

  - B - Bicycles (`azone_prop_sov_dvmt_diverted.csv`) : Network improvements, incentives, and technologies that encourage bicycling and other light-weight vehicle travel

  - C - Vehicle Travel Cost (`azone_hh_veh_own_taxes.csv`) and (`region_prop_externalities_paid.csv`) : Combination of fuel prices and charges to pay for roadway costs and possibly externalities

  - D - DemandManagement (`bzone_travel_demand_mgt.csv`) : Programs to encourage less private vehicle travel

  - E - Driving Efficiency (`marea_operations_deployment.csv`) and (`marea_speed_smooth_ecodrive.csv`) and (`other_ops_effectiveness.csv`) : Driving efficiency by increasing implementation of ITS

  - F - Technology Mix and CI (`marea_transit_powertrain_prop.csv`) and (`region_carsvc_powertrain_prop.csv`) and (region_comsvc_powertrain_prop.csv`) : Vehicle technology mix and carbon intensity of fuels.

  - G - Fuel Price (`azone_fuel_power_cost.csv`) : Real fuel price in 2010 USD

  - I - Income (`azone_fuel_power_cost.csv`) : Real average household income in 2010 USD

  - L - LandUse (`azone_hhsize_targets.csv`) and (`bzone_urban_du_proportions.csv`) : Distribution of population and employment by place type

  - P - Parking (`bzone_parking.csv`) : The extent of paid parking and its price

  - T - Transit (`marea_transit_service.csv`) : The extent and frequency of transit service

  - V - Vehicle Characteristics (`azone_hh_veh_mean_age.csv`) and (`azone_lttrk_prop`): The combination of fuel prices and vehicle travel charges to pay for roadways and to pay for externalities such as carbon pricing

 For each category, you should define the scenario levels you would like to run. For each scenario level you need to change an input based on the scenario definition. 
 
 You need to have each scenario level as a row in this table. The input column should be populated with the modified input file names for each scenario level.

### defs

`VERSPM_Scenarios/defs` directory contains the same files as the `/defs` directory in VERSPM, but the `model_parameters.json` is different.:

```
[
  

  {
    "NAME": "ModelFolder",
    "VALUE": "VERSPM_base_model",
    "TYPE": "character",
    "UNITS": "NA",
    "PROHIBIT": "NA",
    "SIZE": 20,
    "ISELEMENTOF": ""
  },
  {
    "NAME": "ScenarioInputFolder",
    "VALUE": "scenario_root",
    "TYPE": "character",
    "UNITS": "NA",
    "PROHIBIT": "NA",
    "SIZE": 20,
    "ISELEMENTOF": ""
  },
  {
    "NAME" : "ScenarioManagerFile",
    "VALUE": "verspm_scenario_manager.csv",
   "TYPE": "character",
   "UNITS": "NA",
   "PROHIBIT": "NA",
   "SIZE": 30,
   "ISELEMENTOF": ""
  },
  {
    "NAME" : "ScenarioOutputFolder",
    "VALUE": "scenarios",
   "TYPE": "character",
   "UNITS": "NA",
   "PROHIBIT": "NA",
   "SIZE": 20,
   "ISELEMENTOF": ""
  },  
  {
    "NAME" : "NWorkers",
    "VALUE": "6",
    "TYPE" : "integer",
    "UNITS" : "NA",
    "PROHIBIT" : "c('NA', '< 0')",
    "ISELEMENTOF" : ""
  }
]

                                                                                                                                                                                                                                                         
```
** Model folder : The VERSPM base model folder name 
** ScenarioInputFolder: Folder name for scenario root where scenario manager file is located. All the scenario level folders will be created here
** ScenarioManagerFile : Scenario manager database file name
** ScenarioOutputFolder: Name of the folder where all the scenarios are created


### Running VERSPM_Scnearios

Running VERSPM_Scenario has 5 major steps. After initalizing the module there are 5 modules to call


** NewScenarioSet : This module creates the required categories and scenarios json files from csv database. It also creates the folder structure and required inputs for all scenario levels  
** BuildScenarios: This module creates all possible scnearios which are defined in previous step. It copies the base VERSPM files for each scenario folder 
** RunScenarios : This module runs all scenarios 
** VERSPMResults: This model summarizes all different scenario outputs from datastor to standard format
** ViewResults:  This module create the visualization and summaries for different performance measures 

```{r, echo=FALSE, message=FALSE, warning=FALSE}

library(visioneval)


ptm <- proc.time()

#Initialize model
#----------------
initializeModel(
  ModelScriptFile = "run_model.R",
  ParamDir = "defs",
  RunParamFile = "run_parameters.json",
  GeoFile = "geo.csv",
  ModelParamFile = "model_parameters.json",
  LoadDatastore = FALSE,
  DatastoreName = NULL,
  SaveDatastore = TRUE
)

#Run all demo module for all years
#---------------------------------
for(Year in getYears()) {
  
  runModule(
    ModuleName = "NewScenarioSet",
    PackageName = "VEScenario",
    RunFor = "AllYears",
    RunYear = Year
  )  
  
  runModule(
    ModuleName = "BuildScenarios",
    PackageName = "VEScenario",
    RunFor = "AllYears",
    RunYear = Year
  )
  runModule(
    ModuleName = "RunScenarios",
    PackageName = "VEScenario",
    RunFor = "AllYears",
    RunYear = Year
  )
  runModule(
    ModuleName = "VERSPMResults",
    PackageName = "VEScenario",
    RunFor = "AllYears",
    RunYear = Year
  )
  runModule(
    ModuleName = "ViewResults",
    PackageName = "VEScenario",
    RunFor = "AllYears",
    RunYear = Year
  )
}

```

