library(visioneval)
source("VisionEval.R")
rs <- openModel("VERSPM")$copy("RSPM-Test")
rp <- openModel("VERPAT")$copy("RPAT-Test")
mm <- openModel("VERSPM_MM")$copy("RSPMMM-Test")
st <- openModel("VE-State-Staged")$copy("VE-State-Test")
rs$run()
rp$run()
mm$run()
st$run()
